### ISSUE TITLE
Multiline output capture

### ISSUE THREAD

**Issue by AsterOps** [treydock/ssh_exporter#22]
Hey, first thank you for this awesome exporter.
I would ask you about information of capture output of monitoring disk status in RAID.
I ssh session I use
```
[root@ESXI-SRV:~] /opt/smartstorageadmin/ssacli/bin/ssacli ctrl slot=8 pd all show status

   physicaldrive 5I:0:1 (port 5I:box 0:bay 1, 72 GB): OK
   physicaldrive 5I:0:2 (port 5I:box 0:bay 2, 72 GB): OK
   physicaldrive 5I:0:3 (port 5I:box 0:bay 3, 72 GB): OK
   physicaldrive 6I:0:5 (port 6I:box 0:bay 5, 960 GB): OK
   physicaldrive 6I:0:6 (port 6I:box 0:bay 6, 960 GB): OK
   physicaldrive 6I:0:7 (port 6I:box 0:bay 7, 960 GB): OK
   physicaldrive 6I:0:8 (port 6I:box 0:bay 8, 960 GB): OK

[root@ESXI-SRV:~] 
```
to monitor disks. Is it possible to capture statuses (`OK` or `Failed`) in any of these lines using `command_expect` regex?
I have in my `ssh_exporter.yaml`:

```
modules:
  default:
    user: prometheus
    private_key: /home/prometheus/.ssh/id_rsa
    command: /opt/smartstorageadmin/ssacli/bin/ssacli ctrl slot=8 pd all show status
    #command_expect: "OK"
    command_expect: "Failed"
    timeout: 5
    output_metric: true
```
I tried both `OK` and both `Failed` status but if I test using `curl` command I receive in field `ssh_output` total mess: 
```
curl http://localhost:9312/ssh?target=10.1.1.50:22
# HELP ssh_duration_seconds How long the SSH check took in seconds
# TYPE ssh_duration_seconds gauge
ssh_duration_seconds 0.473589795
# HELP ssh_failure Indicates a failure
# TYPE ssh_failure gauge
ssh_failure{reason="command-error"} 0
ssh_failure{reason="command-output"} 0
ssh_failure{reason="error"} 0
ssh_failure{reason="timeout"} 0
# HELP ssh_output The output of the executed command
# TYPE ssh_output gauge
ssh_output{output="\n   physicaldrive 5I:0:1 (port 5I:box 0:bay 1, ..."} 1
# HELP ssh_success SSH connection was successful
# TYPE ssh_success gauge
ssh_success 1
```
I did some experiment with regex which let me grouping output https://regex101.com/r/ywfTv0/1
Actually for me enough will be information if ANY of the listed disk have status differ than `OK`
Regards
