### ISSUE TITLE
Not metrics when a server is not reachable over ssh

### ISSUE THREAD

**Issue by bdoublet91** [treydock/ssh_exporter#29]
Hi,

I dont know if it's the expected behavior but when you have a server that respond in ssh and do an uptime command for example, you have your metric. But when the ssh service is down for whatever reason, the ssh exporter just fail to connect and create a metric with the same value (1) as succeed command.
```
ts=2023-06-30T19:56:35.497Z caller=collector.go:148 level=error target=***:22 msg="Failed to establish SSH connection" err="dial tcp ***:22: connect: no route to host"
```

Could you consider that a non reachable server over ssh is like a fail command output and set a metric to value 0 in ssh_output.
Thanks

**Comment by treydock** [comment]
When SSH fails the metric will have `ssh_success == 0` and `ssh_failure == 1` and the failure will have a reason.  Here is an example alert we use:

```
  - record: ssh_failure_severity
    expr: 0
    labels:
      severity: page
      role: login
      environment: production
  - alert: SSHFailure
    expr: |
      avg_over_time(ssh_success[15m]) == ON(role,environment) group_left(severity)
      (
        ssh_failure_severity
      OR
        ON(role,environment) count by (role,environment)(avg_over_time(ssh_success[15m])) * 0
      )
    for: 5m
    labels:
      alertgroup: ssh
    annotations:
      title: SSH on {{ $labels.host }} has failures
      description:  SSH on {{ $labels.host }} has failures
      reason: "{{ with printf \"ssh_failure{instance='%s'} == 1\" $labels.instance | query }}{{ . | first | label \"reason\" }}{{ end }}"
```

There is another alert we use:

```
 - alert: SSHUnknownFailure
    expr: avg_over_time(ssh_success[15m]) == 0 and on(host) count by(host)(avg_over_time(ssh_failure[15m]) == 1) == 0
    for: 5m
    labels:
      alertgroup: ssh
    annotations:
      title: SSH on {{ $labels.host }} has unknown failures
      description:  SSH on {{ $labels.host }} has unknown failures
```
