### ISSUE TITLE
How to get ssh command output?

### ISSUE THREAD

**Issue by thedemonium** [treydock/ssh_exporter#7]
Greetings!

I am trying to use your ssh_exporter to get the prometheus metric.
I created ssh_exporter.yaml config:

```
modules:
   default:
     user: user
     private_key: /home/user/.ssh/id_rsa
     command: "/ppp active print count"
     timeout: 5
```
prometheus.yml
```
scrape_configs:

  - job_name: ssh
    metrics_path: /ssh
    static_configs:
    - targets:
      - {ssh-host-ip}:22
      labels:
        module: default

    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement:  {prometheus-host-ip}:9312
    - source_labels: [module]
      target_label: __param_module
    metric_relabel_configs:
    - regex: "^(module)$"
      action: labeldrop

  - job_name: ssh-metrics
    metrics_path: /metrics
    static_configs:
    - targets:
      - {prometheus-host-ip}::9312         
```      

After executing the ssh command, a **number** should be returned. 

```
# HELP ssh_duration_seconds How long the SSH check took in seconds
# TYPE ssh_duration_seconds gauge
ssh_duration_seconds 0.386611132
# HELP ssh_failure Indicates a failure
# TYPE ssh_failure gauge
ssh_failure{reason="command-error"} 0
ssh_failure{reason="command-output"} 0
ssh_failure{reason="error"} 0
ssh_failure{reason="timeout"} 0
# HELP ssh_success SSH connection was successful
# TYPE ssh_success gauge
ssh_success 1
```
Please tell me how can I get the output of the ssh command in the form of a metric?
Thanks in advance!

**Comment by treydock** [comment]
This exporter will not return the output in a metric. The only way to return non-numeric things is put them in a label and if the command output changes the label will change and that would cause Prometheus to generate a new timeseries since a timeseries is a unique metric name + label set combination.  The only thing this exporter does with regard to command output is check that the output matches some specific regex, so like I have this in my configs:

```yaml
command: /usr/bin/uptime
command_expect: 'load average'
```

So if the command does not return the string `load average` then the `ssh_failure{reason="command-output"}` metric would have a value of `1`.

I might be able to add a new opt-in metric like `ssh_output{output="<output here, truncated to some length>"}` that is disabled by default.  Would that work?  Per my comments above if something like this is done and the output changes, you'll get a new metric.

**Comment by thedemonium** [comment]
Thank you so much for responding so quickly, Treydock!

If it doesn't make it difficult for you, adding such a feature would be just an excellent solution for my task. Thank you! I will look forward to this feature!

**Comment by treydock** [comment]
Give v1.0.0-rc.0 a try: https://github.com/treydock/ssh_exporter/releases/tag/v1.1.0-rc.0. It added the opt-in `ssh_output` metric.  The README has example of how to enable that metric.

**Comment by thedemonium** [comment]
Thank you!!! 

If it's not difficult, please show me an example prometheus.yml for using the module capture

ssh_exporter.yaml
```
modules:
  default:
    user: user
    private_key: /home/user/.ssh/id_rsa
    command: "/ppp active print count"
    timeout: 5

  capture:
    user: user
    private_key: /home/user/.ssh/id_rsa
    command: "/ppp active print count"
    output_metric: true
    output_truncate: 50

```
prometheus.yml
```
  - job_name: ssh
    metrics_path: /ssh
    static_configs:
    - targets:
      -  {ssh-host-ip}:22
      labels:
        module: capture

    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: {prometheus-host-ip}:9312
    - source_labels: [module]
      target_label: __param_module
    metric_relabel_configs:
    - regex: "^(module)$"
      action: labeldrop

  - job_name: ssh-metrics
    metrics_path: /metrics
    static_configs:
    - targets:
      - {prometheus-host-ip}:9312
```
I tried this but it didn't work; (
Sorry for wasting your time...
